

pool:
  vmImage: ubuntu-latest

steps:

- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'devops-test-v1'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerConnService'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerConnService'
    command: 'build'
    repository: murdoko/pet-clinic
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- script: |
      sudo apt-get install -y rpm
      wget https://github.com/aquasecurity/trivy/releases/download/v0.27.1/trivy_0.27.1_Linux-64bit.deb
      sudo dpkg -i trivy_0.27.1_Linux-64bit.deb
      trivy image murdoko/pet-clinic:latest
  displayName: Image Scan